webjars:
  bootstrap: "4.5.2"
  jquery: "3.5.1"
spring:
  datasource:
    url: "jdbc:mysql://127.0.0.1/test?serverTimezone=JST"
    username: "root"
    password: "password"
    driver-class-name: "com.mysql.jdbc.Driver"
  thymeleaf:
    cache: false
  resources:
    cache:
      period: 0
    static-locations:
    - classpath:/static/
    - file:/var/file/
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: XXX
            clientSecret: XXX
  
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
      